### ISSUE TITLE
Level order example does not work

### ISSUE THREAD

**Issue by lczech** [niemasd/CompactTree#6]
The level order code in the [cookbook](https://niema.net/CompactTree/md_example_cookbook.html) never pushes any nodes to the dequeue expect the root, so it does not traverse the tree. What is the correct way to do this? Also, it would be convenient to have a wrapper around this similar to the pre and post order.

**Comment by niemasd** [comment]
> The level order code in the [cookbook](https://niema.net/CompactTree/md_example_cookbook.html) never pushes any nodes to the dequeue expect the root, so it does not traverse the tree. What is the correct way to do this?

Woops, thanks for catching that! I was adding the cookbook examples in bulk, and that was an error on my part. I just pushed an update (https://github.com/niemasd/CompactTree/commit/f49e46d1f6276bfc43d6d1f04c9e061755c2d95d) that fixes this issue in the cookbook example. It should be correct now (I just tested it); you may need to hard-refresh the cookbook page (e.g. `CTRL+SHIFT+R` or `COMMAND+SHIFT+R`)

> Also, it would be convenient to have a wrapper around this similar to the pre and post order.

Yes, I agree! I need to think of a good way to implement it. The issue is that, to my knowledge, there is no clean equivalent to the `yield` statement in Python (or similar), and I'm not sure how to implement an iterator class (e.g. `levelorder_iterator`) in which the current iterator object can find the node that should come next in a level-order traversal. One option could be to have a static variable in the iterator class that stores the level-order queue, and a `levelorder_iterator` object can move to the next node using that queue, but that might cause issues if a user has multiple independent `levelorder_iterator` objects at the same time on the same tree. I need to think of a good way to design, which is something I hope to do in the future

**Comment by lczech** [comment]
Thanks, the cookbook recipe seems to work now :-)

An iterator class can actually store that as a normal member variable - static would indeed not be a good idea. See for instance [my implementation](https://github.com/lczech/genesis/blob/master/lib/genesis/tree/iterator/levelorder.hpp)
