### ISSUE TITLE
Postorder is backwards

### ISSUE THREAD

**Issue by lczech** [niemasd/CompactTree#8]
When traversing a tree in postorder, the nodes come out backwards. For instance 

```
((e:0.1,a:0.1)x:0.1,(b:0.1,d:0.1)y:0.1,c:0.1)r;
```

with

```
for(auto it = tree.postorder_begin(); it != tree.postorder_end(); ++it) {
    std::cout << tree.get_label(*it) << "\n";
}
```

gives order

```
c
d
b
y
a
e
x
r
```

which is bottom up. It is still a correct postorder travels, so that's all right, but at least I think the cookbook should mention that the order is backwards as compared to the Newick string. Even better would be if the iterator respects the original order of course.

**Comment by niemasd** [comment]
Thanks for highlighting this! This is actually expected behavior: because of how CompactTree allocates the nodes, for a tree containing *n* nodes, a pre-order traversal is literally just an iteration over the integers from 0 to *n*-1 (inclusive), and a post-order traversal is literally just an iteration over the integers from *n*-1 to 0 (inclusive), so both are *super* fast. I don't have plans to change this in the future, as it would break this very fast iteration

But I agree that the documentation should be more explicit about this, as users may not realize this and may accidentally write code depending on the order of the elements beyond just "parent has already been visited" in pre-order or "children have already been visited" in post-order. I have just pushed an update (https://github.com/niemasd/CompactTree/commit/c9a7593c738ce423f768f99b0f51630a67c9df74) that adds this clarification in the class header comments (so they appear in the class documentation pages) as well as in the cookbook
